### ISSUE TITLE
Direct messages cannot be loaded

### ISSUE THREAD

**Issue by Vistaus** [diamondburned/dissent#260] opened 2024-03-28 17:11 UTC
I just installed Dissent using the latest binary from the releases page. I can open it just fine and log in with my token. Messages from channels load just fine, but direct messages do not. I click the DM button, it flashes all of my chats and then all of the chats disappear again.

OS: Deepin V23

The only thing the output shows is

`18:11:10.450 WRN Broken accounting of active state for widget 0x649be8a88050(GtkWindowHandle) priority=4 code_file=../../../gtk/gtkwidget.c code_line=13239 code_func=gtk_widget_set_active_state glib_domain=Gtk`

**Comment by Vistaus** [comment] 2024-03-28 17:16
Hmm, after receiving a notification from a DM, it did load.

**Comment by diamondburned** [comment] 2024-03-28 22:17
Duplicate of https://github.com/diamondburned/dissent/issues/241

**Closed by diamondburned** 2024-03-28 22:17 UTC

**Comment by Vistaus** [comment] 2024-03-28 22:25
> Duplicate of #241

Weird. I did search for any issues mentioning this, even with the words from the title of that issue, but it didn't show me that particular one.
